apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: learningcenter-supplemental
  namespace: learningcenter-supplemental
spec:
  serviceAccountName: lcs-sa
  fetch:
    - git:
        url: https://github.com/clicktruck/application-templates
        ref: origin/main
        subPath: gitops/tanzu/learningcenter/supplemental/base
        secretRef:
          name: git-https-for-carvel
  deploy:
    - kapp: {}